authors_names = [('Aaron Couch', 'Software Developer', 'DKAN', 'private'), 
                 ('Aaron Krolikowski', 'Researcher', 'Freelance', 'Academia (private)'), 
                 ('Aaron Lee', 'Software Developer', 'Solace Systems', 'Private'), 
                 ('Adelaide Rosa', 'Unknown', 'Unknown', 'Unknown'), 
                 ('Andrew Nicklin', 'Technology, Data, and Open Government Strategist', 'GovEx', 'Academia (private)'), 
                 ('Aubrey Hlavaty', 'Unknown', 'Unknown', 'Unknown'), 
                 ('Barbara Bouton', 'Unknown', 'Unknown', 'Unknown'),
                 ('Brian Borncamp', 'Civic Technologist', 'Unknown', 'Unknown'),
                 ('Carl V. Lewis', 'Data Journalist', 'CVL Digital', 'Private' ),
                 ('Chris Slocum', 'Unknown', 'Unknown', 'Unknown'),
                 ('Christopher Fagiani', 'Software Developer', 'Oracle', 'Private'),
                 ('Clinton Blackburn', 'Software Developer', 'edX', 'Private'),
                ('Cory McCoy', 'Unknown', 'Unknown', 'Unknown'),
                ('Curtis Robbins', 'Unknown', 'Unknown', 'Unknown'),
                ('Daniel Wulf', 'Unknown', 'Unknown', 'Unknown'),
                ('Darren Cotton', 'Director of Community Development & Planning', 'University of Buffalo', 'Academia (private)'),
                ('David Gonzalez', 'Head of Technology and Co-Founder', 'Vizzuality', 'Private'),
                ('Doug Crescenzi', 'Software Developer', 'Upstate Interactive', 'Private'),
                ('Douglas Clark', 'Unknown', 'Unknown', 'Unknown'),
                ('Douglas Mokry', 'Unknown', 'Unknown', 'Unknown'),
                ('Eric Roche', 'Chief Data Officer', 'City of Kansas City', 'City Government'),
                ('Frank Cetera', 'Politician', 'Green Party', 'Public'),
                ('Gary Deardorff', 'Unknown', 'Unknown', 'Unknown'),
                ('James Full', 'Unknown', 'Unknown', 'Unknown'),
                ('Jane Bachmann', 'Sr. Communications Manager', 'DuPont', 'Private'),
                 ('Jason Parker', 'Unknown', 'Unknown', 'Unknown'),
                 ('Jean Moreno', 'Unknown', 'Unknown', 'Unknown'),
                 ('Jeff McAffee', 'Unknown', 'Unknown', 'Unknown'),
                 ('Jennifer Thompson', 'Statistician', 'RLadies', 'Non-Profit'),
                 ('Jesse Griffis', 'Software Developer', 'NBT Solutions', 'Private'),
                 ('Jesse Lecy', 'Assistant Professor', 'Syracuse University', 'Academia (private)'),
                 ('Jim Harvey', 'Partner', 'Technology and Privacy Group', 'Private/Cybersecurity'),
                 ('Jonathan Levy', 'Open Data Program Manager', 'Chicago Department of Innovation & Technology', 'City Government'),
                 ('Jorge Díaz', 'Director for Open Participation and Communities', 'Office of President of Mexico', 'Foreign Government'),
                 ('Joseph Ghosen', 'Routing Specialist','Buffalo Board of Education', 'Public'),
                 ('Jurnell Cockhren', 'Software Developer', 'Sophicware', 'Private'),
                 ('K M', 'Unknown', 'Unknown', 'Unknown'),
                 ('Karyn Tareen', 'President & CEO', 'Geocove', 'Private'),
                 ('Kelly Dodd', 'Unknown', 'Unknown', 'Unknown'),
                 ('Kevin Wilson', 'Data Sceintist', 'The University of Chicago', 'Academia (private)'),
                 ('Kirk McLean', 'Special Assistant to the Deputy Mayor', 'City of Buffalo', 'City Government'),
                 ('Leonard Escudero', 'Unknown', 'Unknown', 'Unknown'),
                 ('Leslie Sheeler', 'Unknown', 'Unknown', 'Unknown'),
                 ('Lynn Harding', 'Unknown', 'Unknown', 'Unknown'),
                 ('Mark Headd', 'Innovation Specialist', '18F', 'Federal Government'),
                 ('Mary Jo Burgess', 'Unknown', 'Unknown', 'Unknown'),
                 ('Meag Doherty', 'Operations Manager', 'OpenGov Foundation', 'Not-for-profit'),
                 ('Monica Stephens', 'Assistant Professor', 'University of Buffalo', 'Academia (private)'),
                 ('Nicholas Josefowitz', 'Director', 'BART', 'City Government'),
                 ('Nitin Vig', 'Civic Technologist', 'McKinsey', 'Private'),
                 ('Paul Crickard', 'Systems Analyst', 'City of Albuquerque', 'City Government'),
                 ('Peter Johnson', 'Researcher', 'University of Waterloo', 'Academia (private)'),
                 ('Peter Smith', 'Unknown', 'Unknown', 'Unknown'),
                 ('Ray Strahl', 'Unknown', 'Unknown', 'Unknown'),
                 ('Robert Galbraith', 'Unknown', 'Unknown', 'Unknown'),
                 ('Samantha Linnett', 'Innovation Program Coordinator', 'City of Syracuse', 'City Government'),
                 ('Scott Davis', 'Remote Monitoring/Data Analyst', 'Aerotek', 'Private'),
                 ('Sean Myers', 'Co-Founder', 'NBT Solutions', 'Government'),
                 ('Seth Etter', 'Civic Technologist', 'OpenGov Foundation', 'Not-for-profit'),
                 ('Stephanie Perry', 'Unknown', 'Unknown', 'Unknown'),
                 ('Susannah Bartlett', 'Analytics Coordinator', 'City of Syracuse', 'City Government'),
                 ('Tom Cappetta', 'Unknown', 'Unknown', 'Unknown'),
                 ('แบงค์ รักนะ', 'Unknown', 'Unknown', 'Unknown'),
                 ("John O'B", 'Unknown', 'Unknown', 'Unknown'),
                  ('Seamus Kraft', 'Civic Technologist', 'OpenGov Foundation', 'Not-for-profit')                  
                ]